- name: Install all required dnf packages
  hosts: nodes
  become: true

  tasks:
    - name: Enable crb
      community.general.dnf_config_manager:
        name: crb
        state: enabled

    - name: Enable epel
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install dnf software
      ansible.builtin.dnf:
        name:
          - gcc
          - g++
          # - clang
          - make
          - cmake
          - git
          - htop
          - btop
          - m4
          - kernel-devel
          - dkms
          - ncurses-libs
          - ncurses-devel
          - ncurses-compat-libs
          - ncdu
          - perl-FindBin
          - perl-File-Copy
          - gmp-devel
          - mpfr-devel
          - libmpc-devel
          - isl-devel
        state: present
