- name: Install gcc in different versions
  hosts: head
  vars:
    versions:
      # - 14.2.0
      # - 13.3.0
      # - 12.4.0
      # - 11.5.0
      # - 10.5.0
      - 8.5.0
    makejobs: 20

  tasks:
    - name: Check if gcc is already installed
      ansible.builtin.stat:
        path: "/apps/gcc"
      register: gcc

    - name: Create folder
      ansible.builtin.file:
        path: "/apps/gcc"
        state: directory
        mode: '0755'

    - name: Create module folder
      when: inventory_hostname in groups['head']
      ansible.builtin.file:
        path: "/apps/modulefiles/gcc"
        state: directory
        mode: '0755'

    - name: Download
      ansible.builtin.get_url:
        url: "https://ftp.fau.de/gnu/gcc/gcc-{{ item }}/gcc-{{ item }}.tar.gz"
        dest: "/tmp/gcc-{{ item }}.tar.gz"
        mode: "0755"
      # when: not gcc.stat.exists
      loop: "{{ versions }}"

    - name: Extract
      ansible.builtin.unarchive:
        src: "/tmp/gcc-{{ item }}.tar.gz"
        remote_src: true
        dest: "/tmp/"
        mode: "0755"
      # when: not gcc.stat.exists
      loop: "{{ versions }}"

    - name: Configure
      ansible.builtin.command:
        cmd: "./configure --prefix /apps/gcc/{{ item }} --disable-multilib"
        chdir: /tmp/gcc-{{ item }}
      # when: not gcc.stat.exists
      loop: "{{ versions }}"

    - name: Build
      ansible.builtin.command:
        cmd: make -j {{ makejobs }}
        chdir: /tmp/gcc-{{ item }}
      # when: not gcc.stat.exists
      loop: "{{ versions }}"

    - name: Install
      ansible.builtin.command:
        cmd: make install-strip
        chdir: /tmp/gcc-{{ item }}
      # when: not gcc.stat.exists
      loop: "{{ versions }}"

    - name: Clean up archive
      ansible.builtin.file:
        path: "/tmp/gcc-{{ item }}.tar.gz"
        state: absent
      loop: "{{ versions }}"

    - name: Clean up src
      ansible.builtin.file:
        path: "/tmp/gcc-{{ item }}"
        state: absent
      loop: "{{ versions }}"

    - name: Modulefiles
      # when: inventory_hostname in groups['head']
      ansible.builtin.template:
        src: "./templates/lmod/gcc-template.j2"
        dest: "/apps/modulefiles/gcc/{{ item }}"
        mode: "0755"
      loop: "{{ versions }}"
