- name: Setup NFS (home, work) on head and compute nodes
  hosts: head
  become: true
  tasks:

    - name: Install necessary packages
      ansible.builtin.package:
        name:
          - xfsprogs
          - nfs-utils
        state: present

    - name: Create mount point /home if it does not exist
      ansible.builtin.file:
        path: /home
        state: directory
        mode: '0755'

    - name: Create mount point /work if it does not exist
      ansible.builtin.file:
        path: /work
        state: directory
        mode: '0777'

    - name: Create mount point /apps if it does not exist
      ansible.builtin.file:
        path: /apps
        state: directory
        mode: '0777'

    - name: Configure NFS export for /home
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/home  *(rw,sync,no_root_squash)"
        create: true
        mode: '0777'

    - name: Configure NFS export for /work
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/work  *(rw,sync,no_root_squash)"
        create: true
        mode: '0777'

    - name: Configure NFS export for /apps
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/apps  *(rw,sync,no_root_squash)"
        create: true
        mode: '0777'

    - name: Export NFS share
      ansible.builtin.command: exportfs -a

    - name: Ensure NFS server is running and enabled
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: true

    # - name: Allow NFS services through the firewall
    #   ansible.posix.firewalld:
    #     service: "{{ item }}"
    #     permanent: true
    #     state: enabled
    #     immediate: true
    #   loop:
    #     - nfs
    #     - rpc-bind
    #     - mountd

    # - name: Reload firewalld to apply changes
    #   ansible.builtin.command: firewall-cmd --reload

- name: Mount /home from head on compute nodes
  hosts: compute
  become: true
  tasks:

    - name: Install NFS client package
      ansible.builtin.package:
        name: nfs-utils
        state: present

    - name: Set SELinux boolean for NFS home directories
      ansible.posix.seboolean:
        name: use_nfs_home_dirs
        state: true
        persistent: true

    - name: Create mount point /home if it does not exist
      ansible.builtin.file:
        path: /home
        state: directory
        mode: '0755'

    - name: Create mount point /work if it does not exist
      ansible.builtin.file:
        path: /work
        state: directory
        mode: '0777'

    - name: Create mount point /apps if it does not exist
      ansible.builtin.file:
        path: /apps
        state: directory
        mode: '0755'

    - name: Mount NFS share from head to /home
      ansible.posix.mount:
        path: /home
        src: "{{ groups['head'][0] }}:/home"
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Mount NFS share from head to /work
      ansible.posix.mount:
        path: /work
        src: "{{ groups['head'][0] }}:/work"
        fstype: nfs
        opts: noacl
        state: mounted

    - name: Mount NFS share from head to /apps
      ansible.posix.mount:
        path: /apps
        src: "{{ groups['head'][0] }}:/apps"
        fstype: nfs
        opts: noacl
        state: mounted

    - name: Add home NFS mount entry to fstab
      ansible.posix.mount:
        path: /home
        src: "{{ groups['head'][0] }}:/home"
        fstype: nfs
        opts: defaults
        state: present

    - name: Add work NFS mount entry to fstab
      ansible.posix.mount:
        path: /work
        src: "{{ groups['head'][0] }}:/work"
        fstype: nfs
        opts: noacl
        state: present

    - name: Add apps NFS mount entry to fstab
      ansible.posix.mount:
        path: /apps
        src: "{{ groups['head'][0] }}:/apps"
        fstype: nfs
        opts: noacl
        state: present

- name: Create /scratch folder
  hosts: all
  tasks:
    - name: Create folder
      ansible.builtin.file:
        path: /scratch
        state: directory
        mode: '0777'
