- name: Install Nvidia GPU driver
  hosts: gpu
  become: true

  tasks:
    - name: Unload Nouveau kernel module
      ansible.builtin.command: modprobe -r nouveau

    - name: Blacklist Nouveau driver
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/blacklist-nouveau.conf
        line: "blacklist nouveau"
        mode: "0755"
        create: true

    - name: Ensure Nouveau is blacklisted
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/blacklist-nouveau.conf
        line: "options nouveau modeset=0"

    - name: Add cuda repo
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo

    - name: Install nvidia driver module
      ansible.builtin.dnf:
        name:
          - "nvidia-driver"
          - "nvidia-settings"
          - cuda
        state: latest
